version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redisData:/data
      - ./redis.conf:/etc/redis/redis.conf
