version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    ports:
      - 15672:15672
      - 5672:5672

  redis:
    image: redis:7.0.5
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-data:/data
